In [2]:
import numpy as np

In [3]:
my_list = [1, 3, 5]
my_array = np.array([1, 2, 3])

In [4]:
print(type(my_list))

<class 'list'>


In [5]:
# Create a numpy array from a list
print(np.array(my_list))

[1 3 5]


In [6]:
# Or from a list of list
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Creating arrays using built-in fuctions
# Return evenly spaced values within a given interval
# start stop step
print(np.arange(0, 10))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [8]:
# Generate arrays of zeroes or ones

print(np.zeros(3))
print(np.zeros((5,5)))
print(np.ones(3))
print(np.ones((3,3)))

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# Return evenly spread numbers over a specified interval
# start, stop, number of elements(not step)
# Unlike numpy.arange(), the stop value is included in the result
# The spacing between values is automatically determined based on the specified amount of values(num)
print(np.linspace(0,10,3))
print(np.linspace(0,5,20))
print(np.linspace(0,5,21))

[ 0.  5. 10.]
[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [10]:
# Random number arrays
print(np.random.rand(2))
print(np.random.rand(5,5))

[0.67938072 0.39345382]
[[0.85283223 0.12759953 0.09226369 0.52694374 0.70146559]
 [0.3037356  0.70287986 0.62180543 0.89919473 0.82774926]
 [0.81461201 0.13594596 0.34870226 0.54978763 0.61617187]
 [0.16823205 0.2558783  0.82036912 0.90575996 0.2980498 ]
 [0.99361497 0.6246071  0.95184089 0.58681472 0.41218195]]


In [11]:
# From normal distribution
print(np.random.randn(2))
print(np.random.randn(5,5))

[-1.40109361  1.11637751]
[[-1.29376632  1.03479403 -0.8102527   0.69144441 -0.1268092 ]
 [ 0.43820103 -0.27004351 -0.57530521  0.78912154  0.56074678]
 [-0.28031207 -0.74821809 -0.00337692  0.891102    2.88551427]
 [ 1.05807098  1.45647492  0.43566472 -1.51735829  0.41034405]
 [-2.0339367  -1.4112797   1.54920946 -1.48702686  1.16868299]]


In [12]:
# Random integers from low (inclusive) to high (exclusive)
print(np.random.randint(1,100))

40


In [13]:
# 9 random integers between 1 and 100 will be printed.
print(np.random.randint(1,100,9))

[41 57 81 56 67 54 40 77 20]


In [14]:
# Seeding for reproducable results
np.random.seed(77)
print(np.random.rand(2))

[0.91910903 0.6421956 ]


In [15]:
# Storing
arr = np.arange(25) # numbers from 0 to 24
ranarr = np.random.randint(0, 50, 10) # 10 random numbers between 0 and 50
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[43 37 24 31 32 39 44 19 32 36]


In [16]:
# reshape: Returns an array containing the same data with a new shape
print(arr.reshape(5, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [17]:
# Max, Min and their index positions
print(ranarr.max())
print(ranarr.argmax()) # returns index of maximum elements
print(ranarr.min())

44
6
19


In [18]:
# Creating sample array
arr = np.arange(0, 11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [19]:
# Bracket indexing and selection - similar to Python lists
# Get value at an index
print(arr[7])

7


In [20]:
# Get values in a range
print(arr[1:5])

[1 2 3 4]


In [21]:
# Get values in a range
print(arr[0:5])

[0 1 2 3 4]


In [22]:
# Broadcasting
# Setting a value with index range (Broadcasting)
arr[0:5] = 100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [23]:
# Reset array, why? will be clear soon
arr = np.arange(0, 11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [60]:
# Important notes on Slices
slice_of_arr = arr[0:6]
print(slice_of_arr)

[ 0 99 99 99 99  5]


In [61]:
# Change Slice
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)
# Changes made are also there in the original array!
# Data is not copied, it is a view of the original array!
# This avoids memory problems

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9]


In [26]:
# To get a copy we need to be explicit
arr_copy = arr.copy()
print(arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [27]:
# 2D arrays
arr_2D = np.array(([5, 10, 15], [20, 25, 30], [30, 40, 45]))
print(arr_2D)

[[ 5 10 15]
 [20 25 30]
 [30 40 45]]


In [28]:
# Indexing row
print(arr_2D[1])

[20 25 30]


In [29]:
# Getting individual element value
# Syntax is arr_2D[row][column] or arr_2D[row, col]
print(arr_2D[1][0])
print(arr_2D[1, 0])

20
20


In [30]:
# 2D array slicing
# Shape (2,2) from top right corner
print(arr_2D[:2, 0:])
print(arr_2D[:2, 1:])
print(arr_2D[:2, 2:])

[[ 5 10 15]
 [20 25 30]]
[[10 15]
 [25 30]]
[[15]
 [30]]


In [31]:
# Conditional Selection
arr = np.arange(0, 11)
print(arr)

# Check each element of the array against the condition arr>4
# which returns a boolean array where
# each element is True if the corresponding element in arr is greater than 4, and False otherwise
print(arr>4)

[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True  True]


In [32]:
# Store boolean results in another array
bool_arr = arr> 4
print(bool_arr)

[False False False False False  True  True  True  True  True  True]


In [33]:
# Select only those elements from the arr array where
# the corresponding element in bool_arr is True
# It effectively filters out the elements of arr where the condition arr>4 is True
print(arr[bool_arr])
print(arr[arr> 4])

[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [34]:
arr = np.arange(0, 10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
# Basic arithmetic
print(arr+arr)
print(arr-arr)
print(arr*arr)

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]


In [36]:
print(arr/arr)
# This will raise a Warning on division by zero, but not an error!
# It just fills the spot with nan

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\Administrator.DAI-PC2\AppData\Local\Temp\ipykernel_5384\2200395042.py:1: RuntimeWarning: invalid value encountered in divide
  print(arr/arr)


In [37]:
# Also a warning (but not an error) relating to infinty
print(1/arr)

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


C:\Users\Administrator.DAI-PC2\AppData\Local\Temp\ipykernel_5384\95783187.py:2: RuntimeWarning: divide by zero encountered in divide
  print(1/arr)


In [38]:
print(arr**3)

[  0   1   8  27  64 125 216 343 512 729]


In [39]:
# Universal functions
# Taking Square Roots
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [40]:
# Calculating exponential (e^)
print(np.exp(arr))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [41]:
# Trigonometric Functions like sine
print(np.sin(arr))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [42]:
# Taking the Natural Logarithm
print(np.log(arr))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\Administrator.DAI-PC2\AppData\Local\Temp\ipykernel_5384\3278392787.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [43]:
# Summary statistics
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var())
print(arr.std())

45
4.5
9
0
8.25
2.8722813232690143


In [44]:
# 2D arrays 
# This is a 2-Dimensional array with 3 rows and 4 columns
arr_2D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
# Sum all the columns for each row (e.g. 1+5+9, 2+6+10, etc)
print(arr_2D.sum(axis=0))

[15 18 21 24]


In [46]:
# Row and column count
print(arr_2D.shape)

(3, 4)


In [47]:
print(arr_2D.sum(axis=1))

[10 26 42]


In [48]:
print(arr_2D.sum())

78
