In [1]:
import numpy as np

#### Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [11]:
arr = np.random.randint(1, 100, 25).reshape(5, 5)
specified_number = 45

print("Numbers greater than specified number", specified_number)
print("-->", arr[arr>specified_number])

print("Numbers less than specified number", specified_number)
print("-->", arr[arr<specified_number])

Numbers greater than specified number 45
--> [67 83 83 97 86 76 85 50 66 46 83 47 54 46 58 87 52 97]
Numbers less than specified number 45
--> [17 14  5 35 40 25 44]


#### Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.

In [23]:
arr = np.random.randint(1, 100, 25).reshape(5, 5)
specified_number = 45
replacement = 33
print("Original array: ")
print(arr)
print(f"\nReplacing numbers less than specified number {specified_number} with {replacement}.")
print(np.where(arr < specified_number, replacement, arr))
print(f"\nReplacing numbers equal to specified number {specified_number} with {replacement}.")
print(np.where(arr == specified_number, replacement, arr))
print(f"\nReplacing numbers greater than specified number {specified_number} with {replacement}.")
print(np.where(arr > specified_number, replacement, arr))

Original array: 
[[51 75 85 42  9]
 [81 23 62 35 25]
 [87 27 16 33 70]
 [65 87 38 73 19]
 [78 93 23 35 28]]

Replacing numbers less than specified number 45 with 33.
[[51 75 85 33 33]
 [81 33 62 33 33]
 [87 33 33 33 70]
 [65 87 33 73 33]
 [78 93 33 33 33]]

Replacing numbers equal to specified number 45 with 33.
[[51 75 85 42  9]
 [81 23 62 35 25]
 [87 27 16 33 70]
 [65 87 38 73 19]
 [78 93 23 35 28]]

Replacing numbers greater than specified number 45 with 33.
[[33 33 33 42  9]
 [33 23 33 35 25]
 [33 27 16 33 33]
 [33 33 38 33 19]
 [33 33 23 35 28]]


#### Write a NumPy program to create an array of equal shape and data type of a given array.

In [30]:
arr1 = np.random.randint(0, 100, 12).reshape(3, 4)
rows = arr1.shape[0]
columns = arr1.shape[1]

arr2 = np.random.randint(0, 100, rows*columns).reshape(rows, columns)
print(arr2)

[[57 38 26 70]
 [46 72 59 79]
 [14 36 97  8]]


#### Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.

In [33]:
three_D_array = np.random.randint(1, 1000, 60).reshape(3, 5, 4)
print(three_D_array)

[[[402 714 713  61]
  [906 505 355 916]
  [817 868  76  99]
  [223   5 146 202]
  [774 440 179 617]]

 [[219 201 901 269]
  [544  44 311 424]
  [651 213 567 730]
  [455 180 893 633]
  [213  91 242 629]]

 [[410 655 300 453]
  [484 624 232 942]
  [932  18 447 598]
  [285 548 204 683]
  [259 333 969 131]]]


#### Write a NumPy program to multiply two given arrays of same size element-by-element.

In [36]:
arr1 = np.random.randint(0, 20, 9).reshape(3, 3)
arr2 = np.random.randint(0, 20, 9).reshape(3, 3)

print("Array 1: \n", arr1)
print("\nArray 2: \n", arr2)
print("\nElement wise multiplication: \n", arr1*arr2)

Array 1: 
 [[ 3  3 15]
 [15 19 13]
 [ 2 15  8]]

Array 2: 
 [[ 9  5  0]
 [ 8 14  9]
 [ 0 15  8]]

Element wise multiplication: 
 [[ 27  15   0]
 [120 266 117]
 [  0 225  64]]
